spring:
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource 
     url: jdbc:mysql://192.168.1.240/emeng
     username: root
     password: qazwsx123
     # driver-class-name: com.mysql.jdbc.Driver
     driverClassName: com.mysql.jdbc.Driver
     initialSize: 5
  profiles:
    active: dev
    
# freemarker  配置
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  mvc:
    static-path-pattern: /static/**